name: Generate Links Page

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate links.html with folder structure
        run: |
          echo "<!DOCTYPE html><html><head><title>所有 SingleFile 頁面</title></head><body><h1>所有 SingleFile 頁面</h1><ul>" > links.html
          for dir in $(find . -type d -name "20*"); do
            echo "<h2>${dir}</h2><ul>" >> links.html
            for file in $(find $dir -type f -name "*.html"); do
              url=$(echo $file | jq -Rr @uri)
              name=$(basename "$file" | sed 's/[^a-zA-Z0-9._-]/_/g') # 替換特殊字元
              echo "<li><a href='$url'>$name</a></li>" >> links.html
            done
            echo "</ul>" >> links.html
          done
          echo "</ul></body></html>" >> links.html

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add links.html
          git commit -m "Update links.html with folder structure"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main
