name: Generate Links Page

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate links.html
        run: |
          echo "<!DOCTYPE html><html><head><title>所有 SingleFile 頁面</title></head><body><h1>所有 SingleFile 頁面</h1><ul>" > links.html
          for file in $(find . -name "*.html" -not -name "links.html"); do
            encoded_url=$(echo "$file" | jq -Rr @uri) # 將文件名進行 URL 編碼
            name=$(basename "$file")
            echo "<li><a href='$encoded_url'>$name</a></li>" >> links.html
          done
          echo "</ul></body></html>" >> links.html

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add links.html
          git commit -m "Update links.html"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main
