name: Generate Links Page

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate links.html with folder structure
        run: |
          echo "<!DOCTYPE html><html><head><title>所有 SingleFile 頁面</title><style>ul { list-style: none; padding: 0; } li { margin: 5px 0; } a { text-decoration: none; color: #007bff; } a:hover { text-decoration: underline; }</style></head><body><h1>所有 SingleFile 頁面</h1><ul>" > links.html
          for dir in $(find . -type d -name "20*"); do
            dir_name=$(basename "$dir")
            echo "<h2>$dir_name</h2><ul>" >> links.html
            for file in $(find "$dir" -type f -name "*.html"); do
              # 修正檔名及 URL
              clean_name=$(basename "$file" | sed 's/[^a-zA-Z0-9._-]/_/g' | sed 's/_html$/.html/')
              clean_url=$(realpath --relative-to=. "$file" | jq -Rr @uri)
              
              # 輸出到 links.html
              echo "<li><a href='$clean_url'>$clean_name</a></li>" >> links.html
            done
            echo "</ul>" >> links.html
          done
          echo "</ul></body></html>" >> links.html

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add links.html
          git commit -m "Update links.html with folder structure"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main
